GET http://localhost:3000/item HTTP/1.1



### 
GET http://localhost:3000/item/1 HTTP/1.1

### 

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "first_name": "walid", 
    "last_name": "walid", 
    "email": "walid@gmail.com",
    "password": "walid", 
    "wallet": 0
}


### 

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "walid@gmail.com",
    "password": "walid", 
}